In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification

In [2]:
trainangles_t = np.load('trainangles_t.npy', allow_pickle = True)
trainenergy_t = np.load('trainenergy_t.npy', allow_pickle = True)
trainbinfrac_t = np.load('trainbinfrac_t.npy', allow_pickle = True)
trainrsq_t = np.load('trainrsq_t.npy', allow_pickle = True)
traindedx_t = np.load('traindedx_t.npy', allow_pickle = True)
pdg2_train = np.load('pdg2_train.npy')

In [3]:
testangles_t = np.load('testangles_t.npy', allow_pickle = True)
testenergy_t = np.load('testenergy_t.npy', allow_pickle = True)
testbinfrac_t = np.load('testbinfrac_t.npy', allow_pickle = True)
testrsq_t = np.load('testrsq_t.npy', allow_pickle = True)
testdedx_t = np.load('testdedx_t.npy', allow_pickle = True)
testisTrack_t = np.load('testisTrack.npy')
pdg2_test = np.load('pdg2_test.npy')

In [75]:
len(testdedx_t)

79124

# Removing 'other' from pdg testing

In [4]:
pdg3_list = []

for i in range(len(pdg2_train)):
    if pdg2_train[i] != 0:
        pdg3_list.append(pdg2_train[i])

In [5]:
pdg3_train = np.array(pdg3_list)

In [6]:
len(pdg3_train)

71540

In [7]:
pdg3_train[:50]

array([  13, 2212, 2212,   13, 2212, 2212, 2212,   13, 2212,   13,  211,
         13,   13,   13, 2212,   13, 2212, 2212,   13, 2212, 2212, 2212,
       2212, 2212, 2212, 2212, 2212,   13, 2212, 2212, 2212,   13, 2212,
         13,   13,   13, 2212,   13, 2212,   13,   13,   13, 2212,   13,
       2212, 2212, 2212, 2212, 2212, 2212])

In [8]:
len(np.where(pdg2_train == 0)[0]) + len(pdg3_train)

78513

# Removing 'other' from variables training

In [9]:
other = list(np.where(pdg2_train == 0)[0])

In [10]:
trainangles_list = list(trainangles_t)

In [11]:
for i in sorted(other, reverse = True):
    del trainangles_list[i]

In [12]:
trainangles_new_list = []

trainangles_new_list.append(trainangles_list)

In [13]:
trainangles_new = np.array(trainangles_new_list[0])

In [14]:
trainenergy_list = list(trainenergy_t)

In [15]:
for i in sorted(other, reverse = True):
    del trainenergy_list[i]

In [16]:
trainenergy_new_list = []

trainenergy_new_list.append(trainenergy_list)

In [17]:
trainenergy_new = np.array(trainenergy_new_list[0])

In [18]:
trainbinfrac_list = list(trainbinfrac_t)

In [19]:
for i in sorted(other, reverse = True):
    del trainbinfrac_list[i]

In [20]:
trainbinfrac_new_list = []

trainbinfrac_new_list.append(trainbinfrac_list)

In [21]:
trainbinfrac_new = np.array(trainbinfrac_new_list[0])

In [22]:
trainrsq_list = list(trainrsq_t)

In [23]:
for i in sorted(other, reverse = True):
    del trainrsq_list[i]

In [24]:
trainrsq_new_list = []

trainrsq_new_list.append(trainrsq_list)

In [25]:
trainrsq_new = np.array(trainrsq_new_list[0])

In [26]:
traindedx_list = list(traindedx_t)

In [27]:
for i in sorted(other, reverse = True):
    del traindedx_list[i]

In [28]:
traindedx_new_list = []

traindedx_new_list.append(traindedx_list)

In [29]:
traindedx_new = np.array(traindedx_new_list[0])

# Removing 'other' from pdg testing

In [30]:
pdg3_list_test = []

for i in range(len(pdg2_test)):
    if pdg2_test[i] != 0:
        pdg3_list_test.append(pdg2_test[i])

In [31]:
pdg3_test = np.array(pdg3_list_test)

In [32]:
len(pdg3_test)

74747

In [33]:
pdg3_test[:50]

array([ 211,   13,   13, 2212,   13,   13, 2212,   13, 2212,   13,   13,
       2212,   13,   13,   13, 2212,   13,   13,   13,   13, 2212,   13,
         13, 2212,   13,   13,   13,   13,   13,   13, 2212,   13,   13,
         13,   13, 2212,   13, 2212,   13,   13,   13, 2212, 2212,   13,
       2212, 2212,   13, 2212, 2212,   13])

In [34]:
len(np.where(pdg2_test == 0)[0]) + len(pdg3_test)

79124

In [35]:
len(pdg3_test)

74747

# Removing 'other' from variables testing

In [36]:
other_test = list(np.where(pdg2_test == 0)[0])

In [37]:
len(other_test)

4377

In [38]:
testangles_list = list(testangles_t)

In [39]:
for i in sorted(other_test, reverse = True):
    del testangles_list[i]

In [40]:
testangles_new_list = []

testangles_new_list.append(testangles_list)

In [41]:
testangles_new = np.array(testangles_new_list[0])

In [42]:
testenergy_list = list(testenergy_t)

In [43]:
for i in sorted(other_test, reverse = True):
    del testenergy_list[i]

In [44]:
testenergy_new_list = []

testenergy_new_list.append(testenergy_list)

In [45]:
testenergy_new = np.array(testenergy_new_list[0])

In [46]:
testbinfrac_list = list(testbinfrac_t)

In [47]:
for i in sorted(other_test, reverse = True):
    del testbinfrac_list[i]

In [48]:
testbinfrac_new_list = []

testbinfrac_new_list.append(testbinfrac_list)

In [49]:
testbinfrac_new = np.array(testbinfrac_new_list[0])

In [50]:
testrsq_list = list(testrsq_t)

In [51]:
for i in sorted(other_test, reverse = True):
    del testrsq_list[i]

In [52]:
testrsq_new_list = []

testrsq_new_list.append(testrsq_list)

In [53]:
testrsq_new = np.array(testrsq_new_list[0])

In [110]:
testdedx_list = list(testdedx_t)

In [111]:
len(testdedx_t)

79124

In [112]:
for i in sorted(other_test, reverse = True):
    del testdedx_list[i]

In [113]:
testdedx_new_list = []

testdedx_new_list.append(testdedx_list)

In [114]:
testdedx_new = np.array(testdedx_new_list[0])

In [115]:
len(testdedx_new)

74747

In [116]:
len(testangles_new)

74747

In [117]:
len(pdg3_test)

74747

In [118]:
len(testdedx_new)

74747

# Training data sets

In [119]:
x_train = np.array(list(zip(trainangles_new, trainbinfrac_new, trainenergy_new, trainrsq_new, traindedx_new)))

In [120]:
x_train

array([[1.43126162e+01, 2.02380952e-01, 1.81911126e-01, 9.93120234e-01,
        3.46223368e+02],
       [1.51185943e+00, 2.05128205e-01, 2.36471266e-01, 9.79858409e-01,
        6.37410446e+02],
       [5.77915535e+00, 2.05882353e-01, 2.86857754e-01, 9.97228315e-01,
        1.87292996e+03],
       ...,
       [2.36683276e+00, 2.20289855e-01, 2.10825384e-01, 9.99218920e-01,
        2.55594516e+03],
       [2.46280738e+00, 2.00361011e-01, 1.97115883e-01, 9.99439636e-01,
        2.39284177e+02],
       [3.43693059e+00, 2.14285714e-01, 1.91930220e-01, 9.98836453e-01,
        6.99412575e+02]])

In [121]:
y_train = pdg3_train

In [122]:
len(y_train)

71540

In [123]:
len(traindedx_new)

71540

# Create and train BDT

In [124]:
base = DecisionTreeClassifier(max_depth=5)
bdt = AdaBoostClassifier(base_estimator=base, n_estimators=200, random_state=0)
bdt.fit(x_train, y_train)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=5),
                   n_estimators=200, random_state=0)

In [125]:
bdt.score(x_train, y_train)

0.826027397260274

In [126]:
threecat_pred_train = bdt.predict(x_train)
np.save('threecatdedx_pred_train.npy', threecat_pred_train)

# Testing data sets

In [127]:
x_test = np.array(list(zip(testangles_new, testbinfrac_new, testenergy_new, testrsq_new, testdedx_new)))

In [128]:
y_test = pdg3_test

In [129]:
set(y_test)

{13, 211, 2212}

# Create and test BDT

In [130]:
base = DecisionTreeClassifier(max_depth=5)
bdt = AdaBoostClassifier(base_estimator=base, n_estimators=200, random_state=0)
bdt.fit(x_test, y_test)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=5),
                   n_estimators=200, random_state=0)

In [131]:
bdt.score(x_test, y_test)

0.82450131777864

In [132]:
threecat_pred_test = bdt.predict(x_test)
np.save('threecatdedx_pred_test.npy', threecat_pred_test)

# Confusion Matrix training 

In [133]:
#PDGs predicted by the 4 cat BDT
pred_train = threecat_pred_train
pred_test = threecat_pred_test

In [134]:
pred_train[:100]

array([  13, 2212, 2212,   13,   13, 2212, 2212,   13, 2212,   13, 2212,
         13,   13,   13, 2212,   13, 2212, 2212,   13, 2212,   13, 2212,
       2212, 2212, 2212, 2212, 2212,   13, 2212, 2212, 2212,   13, 2212,
       2212,   13,   13, 2212,   13,   13,   13,   13,   13, 2212,   13,
       2212, 2212, 2212,   13, 2212, 2212,   13, 2212, 2212,   13,   13,
         13,   13,  211,   13,  211,   13, 2212, 2212,   13,   13, 2212,
         13,  211, 2212,   13,   13,   13,   13,   13, 2212, 2212,  211,
         13, 2212, 2212,  211, 2212, 2212, 2212,   13, 2212,   13,   13,
         13, 2212,  211,   13,  211,  211, 2212,   13,   13,   13,   13,
       2212])

In [135]:
#True PDG values
pdg3_train[:100]

array([  13, 2212, 2212,   13, 2212, 2212, 2212,   13, 2212,   13,  211,
         13,   13,   13, 2212,   13, 2212, 2212,   13, 2212, 2212, 2212,
       2212, 2212, 2212, 2212, 2212,   13, 2212, 2212, 2212,   13, 2212,
         13,   13,   13, 2212,   13, 2212,   13,   13,   13, 2212,   13,
       2212, 2212, 2212, 2212, 2212, 2212,   13, 2212, 2212,   13,   13,
         13,   13,   13,   13,  211,   13, 2212, 2212,   13,   13, 2212,
         13,  211, 2212,   13,   13,   13,   13,   13, 2212, 2212,  211,
         13, 2212, 2212, 2212, 2212,   13, 2212,   13, 2212,   13,   13,
         13, 2212,   13,   13,  211,  211,  211,   13, 2212,   13,   13,
       2212])

In [136]:
true_muon_train = np.where(pdg3_train == 13)[0]
true_proton_train = np.where(pdg3_train == 2212)[0]
true_pion_train = np.where(pdg3_train == 211)[0]

In [137]:
pred_muon_train = np.where(pred_train == 13)[0]
pred_proton_train = np.where(pred_train == 2212)[0]
pred_pion_train = np.where(pred_train == 211)[0]

In [138]:
mumu_train = len(np.intersect1d(true_muon_train, pred_muon_train))/len(true_muon_train)
protprot_train = len(np.intersect1d(true_proton_train, pred_proton_train))/len(true_proton_train)
pipi_train = len(np.intersect1d(true_pion_train, pred_pion_train))/len(true_pion_train)

In [139]:
mumu_train

0.805417267129569

In [140]:
protprot_train

0.9052112794377083

In [141]:
pipi_train

0.41098735133094205

In [142]:
muprot_train = len(np.intersect1d(true_muon_train, pred_proton_train))/len(true_muon_train)
mupi_train = len(np.intersect1d(true_muon_train, pred_pion_train))/len(true_muon_train)

In [143]:
muprot_train

0.12236342198349273

In [144]:
mupi_train

0.0722193108869383

In [145]:
protmu_train = len(np.intersect1d(true_proton_train, pred_muon_train))/len(true_proton_train)
protpi_train = len(np.intersect1d(true_proton_train, pred_pion_train))/len(true_proton_train)

In [146]:
protmu_train

0.08815210999411946

In [147]:
protpi_train

0.006636610568172272

In [148]:
pimu_train = len(np.intersect1d(true_pion_train, pred_muon_train))/len(true_pion_train) 
piprot_train = len(np.intersect1d(true_pion_train, pred_proton_train))/len(true_pion_train)

In [149]:
pimu_train

0.40324712101189353

In [150]:
piprot_train

0.18576552765716442

# Confusion Matrix testing

In [151]:
true_muon_test = np.where(pdg3_test == 13)[0]
true_proton_test = np.where(pdg3_test == 2212)[0]
true_pion_test = np.where(pdg3_test == 211)[0]

In [152]:
pred_muon_test = np.where(pred_test == 13)[0]
pred_proton_test = np.where(pred_test == 2212)[0]
pred_pion_test = np.where(pred_test == 211)[0]

In [153]:
mumu_test = len(np.intersect1d(true_muon_test, pred_muon_test))/len(true_muon_test)
protprot_test = len(np.intersect1d(true_proton_test, pred_proton_test))/len(true_proton_test)
pipi_test = len(np.intersect1d(true_pion_test, pred_pion_test))/len(true_pion_test)

In [154]:
mumu_test

0.8170160217845608

In [155]:
protprot_test

0.9012039086541057

In [156]:
pipi_test

0.3987579669880699

In [157]:
muprot_test = len(np.intersect1d(true_muon_test, pred_proton_test))/len(true_muon_test)
mupi_test = len(np.intersect1d(true_muon_test, pred_pion_test))/len(true_muon_test)

In [158]:
muprot_test

0.12931416629725792

In [159]:
mupi_test

0.053669811918181244

In [160]:
protmu_test = len(np.intersect1d(true_proton_test, pred_muon_test))/len(true_proton_test)
protpi_test = len(np.intersect1d(true_proton_test, pred_pion_test))/len(true_proton_test)

In [161]:
protmu_test

0.0904281163958322

In [162]:
protpi_test

0.008367974950062085

In [163]:
pimu_test = len(np.intersect1d(true_pion_test, pred_muon_test))/len(true_pion_test) 
piprot_test = len(np.intersect1d(true_pion_test, pred_proton_test))/len(true_pion_test)

In [164]:
pimu_test

0.4064389606144795

In [165]:
piprot_test

0.19480307239745057